apiVersion: v1
entries:
  bindizr-stack:
  - apiVersion: v2
    appVersion: 0.1.0-beta.4
    created: "2026-06-08T16:57:51.345641642Z"
    description: Bindizr DNS control plane with BIND9 authoritative DNS pods.
    digest: 7876a6d0ac998d3d2d1a616ed369f4c3a155ad0653a33e59bdc73969675f7f62
    home: https://github.com/kweonminsung/bindizr
    keywords:
    - dns
    - bindizr
    - bind9
    - kubernetes
    - helm
    maintainers:
    - email: kevin136583@gmail.com
      name: kweonminsung
    name: bindizr-stack
    sources:
    - https://github.com/kweonminsung/bindizr
    type: application
    urls:
    - https://kweonminsung.github.io/bindizr/charts/bindizr-stack-0.1.0-beta.4.tgz
    version: 0.1.0-beta.4
generated: "2026-06-08T16:57:51.344695535Z"
