apiVersion: v1
entries:
  bindizr-stack:
  - apiVersion: v2
    appVersion: 0.1.0-beta.4
    created: "2026-06-10T20:35:21.093908223Z"
    description: Bindizr DNS control plane with BIND9 authoritative DNS pods.
    digest: 41ce9a344f8feb8bd925c9a034d6599d89a04b224f50d072962f7dd17ac115fc
    home: https://github.com/kweonminsung/bindizr
    keywords:
    - dns
    - bindizr
    - bind9
    - kubernetes
    - helm
    maintainers:
    - email: kevin136583@gmail.com
      name: kweonminsung
    name: bindizr-stack
    sources:
    - https://github.com/kweonminsung/bindizr
    type: application
    urls:
    - https://kweonminsung.github.io/bindizr/charts/bindizr-stack-0.1.0-beta.4.tgz
    version: 0.1.0-beta.4
generated: "2026-06-10T20:35:21.093043647Z"
