apiVersion: v1
entries:
  bindizr-stack:
  - apiVersion: v2
    appVersion: 0.1.0-beta.4
    created: "2026-06-10T20:41:41.710611304Z"
    description: Bindizr DNS control plane with BIND9 authoritative DNS pods.
    digest: 2a51f96a2e5afce827948ad8527e5042305f93526c32ac3862d6199d00904347
    home: https://github.com/kweonminsung/bindizr
    keywords:
    - dns
    - bindizr
    - bind9
    - kubernetes
    - helm
    maintainers:
    - email: kevin136583@gmail.com
      name: kweonminsung
    name: bindizr-stack
    sources:
    - https://github.com/kweonminsung/bindizr
    type: application
    urls:
    - https://kweonminsung.github.io/bindizr/charts/bindizr-stack-0.1.0-beta.4.tgz
    version: 0.1.0-beta.4
generated: "2026-06-10T20:41:41.709708993Z"
