apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bindizr-chart.fullname" . }}-config
  labels:
    {{- include "bindizr-chart.labels" . | nindent 4 }}
data:
  bindizr.conf.toml: |
    [api]
    listen_addr = "{{ .Values.bindizr.api.listenAddr }}"
    listen_port = {{ .Values.bindizr.api.port }}
    authentication_required = {{ .Values.bindizr.api.authenticationRequired }}
    metrics_enabled = {{ .Values.bindizr.api.metricsEnabled }}
    external_dns_enabled = {{ .Values.bindizr.api.externalDnsEnabled }}
    openapi_enabled = {{ .Values.bindizr.api.openapiEnabled }}
    {{- with .Values.bindizr.api.tls.existingSecret }}

    [api.tls]
    cert_file = "/etc/bindizr/tls/tls.crt"
    key_file = "/etc/bindizr/tls/tls.key"
    {{- end }}


    [database]
    type = "{{ .Values.bindizr.database.type }}"

    [database.mysql]
    url = ""

    [database.postgresql]
    url = ""
    {{- if or .Values.bindizr.database.tls.mode .Values.bindizr.database.tls.existingSecret }}

    [database.tls]
    {{- with .Values.bindizr.database.tls.mode }}
    mode = "{{ . }}"
    {{- end }}
    {{- if .Values.bindizr.database.tls.existingSecret }}
    ca_file = "/etc/bindizr/db-tls/ca.crt"
    {{- end }}
    {{- end }}

    [dns]
    listen_addr = "{{ .Values.bindizr.dns.listenAddr }}"
    listen_port = {{ .Values.bindizr.dns.port }}
    catalog_zone_name = "{{ .Values.bindizr.dns.catalogZoneName }}"
    zone_history_retention_days = {{ .Values.bindizr.dns.zoneHistoryRetentionDays }}
    scheduler_interval_secs = {{ .Values.bindizr.dns.schedulerIntervalSecs }}


    [dns.notify]
    batch_ms = {{ .Values.bindizr.dns.notify.batchMs }}
    retries = {{ .Values.bindizr.dns.notify.retries }}
    timeout_secs = {{ .Values.bindizr.dns.notify.timeoutSecs }}

    [dns.nsupdate]
    tsig_required = {{ .Values.bindizr.dns.nsupdateTsigRequired }}
    {{- with .Values.bindizr.dns.tls.existingSecret }}

    [dns.tls]
    listen_port = {{ $.Values.bindizr.dns.tls.port }}
    cert_file = "/etc/bindizr/dns-tls/tls.crt"
    key_file = "/etc/bindizr/dns-tls/tls.key"
    {{- end }}

    [dns.transfer]
    cache_max_records = {{ .Values.bindizr.dns.transfer.cacheMaxRecords }}
    require_tls = {{ .Values.bindizr.dns.transfer.requireTls }}

    [dns.tcp]
    idle_timeout_secs = {{ .Values.bindizr.dns.tcp.idleTimeoutSecs }}
    max_connections = {{ .Values.bindizr.dns.tcp.maxConnections }}

    [dns.import]
    timeout_secs = {{ .Values.bindizr.dns.import.timeoutSecs }}
    max_records = {{ .Values.bindizr.dns.import.maxRecords }}

    [dns.zone_defaults]
    ttl = {{ .Values.bindizr.zoneDefaults.ttl }}
    refresh = {{ .Values.bindizr.zoneDefaults.refresh }}
    retry = {{ .Values.bindizr.zoneDefaults.retry }}
    expire = {{ int64 .Values.bindizr.zoneDefaults.expire }}
    minimum_ttl = {{ .Values.bindizr.zoneDefaults.minimumTtl }}

    [logging]
    level = "{{ .Values.bindizr.logging.level }}"
    format = "{{ .Values.bindizr.logging.format }}"
