apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bindizr-chart.fullname" . }}-config
  labels:
    {{- include "bindizr-chart.labels" . | nindent 4 }}
data:
  bindizr.conf.toml: |
    [api]
    listen_addr = "{{ .Values.bindizr.api.listenAddr }}"
    listen_port = {{ .Values.bindizr.api.port }}
    authentication_required = {{ .Values.bindizr.api.authenticationRequired }}
    metrics_enabled = {{ .Values.bindizr.api.metricsEnabled }}
    external_dns_enabled = {{ .Values.bindizr.api.externalDnsEnabled }}
    openapi_enabled = {{ .Values.bindizr.api.openapiEnabled }}
    {{- with .Values.bindizr.api.tls.existingSecret }}
    tls_cert_file = "/etc/bindizr/tls/tls.crt"
    tls_key_file = "/etc/bindizr/tls/tls.key"
    {{- end }}


    [database]
    type = "{{ .Values.bindizr.database.type }}"

    [database.mysql]
    url = ""

    [database.postgresql]
    url = ""

    [dns]
    listen_addr = "{{ .Values.bindizr.dns.listenAddr }}"
    listen_port = {{ .Values.bindizr.dns.port }}
    nsupdate_tsig_required = {{ .Values.bindizr.dns.nsupdateTsigRequired }}
    secondary_addrs = "{{ include "bindizr-chart.secondaryAddrs" . }}"
    zone_history_retention_days = {{ .Values.bindizr.dns.zoneHistoryRetentionDays }}
    scheduler_interval_secs = {{ .Values.bindizr.dns.schedulerIntervalSecs }}


    [dns.notify]
    after_update = {{ .Values.bindizr.dns.notify.afterUpdate }}
    on_startup = {{ .Values.bindizr.dns.notify.onStartup }}
    batch_ms = {{ .Values.bindizr.dns.notify.batchMs }}
    retries = {{ .Values.bindizr.dns.notify.retries }}
    timeout_secs = {{ .Values.bindizr.dns.notify.timeoutSecs }}

    [dns.transfer_cache]
    enabled = {{ .Values.bindizr.dns.transferCache.enabled }}
    max_records = {{ .Values.bindizr.dns.transferCache.maxRecords }}

    [dns.zone_defaults]
    ttl = {{ .Values.bindizr.zoneDefaults.ttl }}
    refresh = {{ .Values.bindizr.zoneDefaults.refresh }}
    retry = {{ .Values.bindizr.zoneDefaults.retry }}
    expire = {{ int64 .Values.bindizr.zoneDefaults.expire }}
    minimum_ttl = {{ .Values.bindizr.zoneDefaults.minimumTtl }}

    [logging]
    level = "{{ .Values.bindizr.logging.level }}"
    format = "{{ .Values.bindizr.logging.format }}"
