{{- if and .Values.bindizr.podDisruptionBudget.enabled (gt (int .Values.bindizr.replicas) 1) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "bindizr-chart.fullname" . }}
  labels:
    {{- include "bindizr-chart.labels" . | nindent 4 }}
spec:
  {{- toYaml .Values.bindizr.podDisruptionBudget.spec | nindent 2 }}
  selector:
    matchLabels:
      {{- include "bindizr-chart.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: bindizr
{{- end }}
