apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bindizr-chart.fullname" . }}-config
  labels:
    {{- include "bindizr-chart.labels" . | nindent 4 }}
data:
  bindizr.conf.toml: |
    [api]
    listen_addr = "{{ .Values.bindizr.api.listenAddr }}"
    listen_port = {{ .Values.bindizr.api.port }}
    require_authentication = {{ .Values.bindizr.api.requireAuthentication }}
    metrics_enabled = {{ .Values.bindizr.api.metricsEnabled }}
    external_dns_enabled = {{ .Values.bindizr.api.externalDnsEnabled }}

    [database]
    type = "{{ .Values.bindizr.database.type }}"

    [database.mysql]
    server_url = ""

    [database.postgresql]
    server_url = ""

    [dns]
    listen_addr = "{{ .Values.bindizr.dns.listenAddr }}"
    listen_port = {{ .Values.bindizr.dns.port }}
    secondary_addrs = "{{ include "bindizr-chart.secondaryAddrs" . }}"
    notify_after_update = {{ .Values.bindizr.dns.notifyAfterUpdate }}
    notify_on_startup = {{ .Values.bindizr.dns.notifyOnStartup }}
    notify_retries = {{ .Values.bindizr.dns.notifyRetries }}
    notify_timeout_secs = {{ .Values.bindizr.dns.notifyTimeoutSecs }}
    nsupdate_allow_unsigned = {{ .Values.bindizr.dns.nsupdateAllowUnsigned }}

    [logging]
    log_level = "{{ .Values.bindizr.logging.level }}"
