{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "bindizr-chart.fullname" . }}
  labels:
    {{- include "bindizr-chart.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["configmaps", "pods", "services"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "bindizr-chart.fullname" . }}
  labels:
    {{- include "bindizr-chart.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "bindizr-chart.serviceAccountName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "bindizr-chart.fullname" . }}
{{- end }}
