{{- if not .Values.bindizr.database.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bindizr-chart.databaseSecretName" . }}
  labels:
    {{- include "bindizr-chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.bindizr.database.secretKey }}: {{ include "bindizr-chart.databaseUrl" . | quote }}
{{- end }}
{{- if .Values.mysql.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bindizr-chart.mysql.fullname" . }}
  labels:
    {{- include "bindizr-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: mysql
type: Opaque
stringData:
  mysql-password: {{ .Values.mysql.auth.password | quote }}
  mysql-root-password: {{ .Values.mysql.auth.rootPassword | quote }}
{{- end }}
{{- if .Values.postgresql.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bindizr-chart.postgresql.fullname" . }}
  labels:
    {{- include "bindizr-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
type: Opaque
stringData:
  postgres-password: {{ .Values.postgresql.auth.password | quote }}
{{- end }}
