setLocal("0.0.0.0:53")
addLocal("[::]:53")
setACL({"0.0.0.0/0", "::/0"})

setServerPolicy(roundrobin)

newServer({address="172.28.0.11:53", name="bind9-1"})
newServer({address="172.28.0.12:53", name="bind9-2"})
