use bindizr_core::model::{
    role_grant::Action,
    transfer::{TransferKind, TransferResult},
};
use bindizr_service::types::{
    BulkRecordsResponse, CreateBulkRecordsRequest, CreateDnssecPolicyRequest, CreateRecordRequest,
    CreateRoleGrantRequest, CreateRoleRequest, CreateSecondaryRequest, CreateTokenRequest,
    CreateTsigKeyRequest, CreateZoneRequest, CreatedTokenResponse, DeleteRecordsResponse,
    DeleteZoneResponse, DnssecDelegationInfo, DnssecDelegationKeyInfo, DnssecDsInfo, DnssecKeyInfo,
    DnssecPolicyResponse, DnssecStatusResponse, EnableDnssecRequest, ErrorResponse,
    ExternalDnsAdjustRequest, ExternalDnsAdjustResponse, ExternalDnsChangesRequest,
    ExternalDnsChangesResponse, ExternalDnsDomainsResponse, ExternalDnsRecord,
    ExternalDnsRecordUpdate, ExternalDnsRecordsResponse, GetDnssecPolicyResponse,
    GetRecordResponse, GetRoleGrantResponse, GetRoleResponse, GetSecondaryResponse,
    GetTokenResponse, GetTsigKeyResponse, GetZoneResponse, HealthResponse, HealthStatus,
    ImportSummary, ImportZoneRequest, ImportZoneResponse, MessageResponse, NotifyCheckResponse,
    PaginatedResponse, Pagination, PermissionsResponse, PermittedActionsResponse, RecordDiff,
    RecordDiffEntry, RecordDiffSummary, RecordDiffValue, RecordItem, RecordResponse,
    RecordValueRequest, RecordWriteResponse, RoleGrantResponse, RoleResponse, RollbackSummary,
    RollbackZoneResponse, RolloverDnssecRequest, SecondaryCheckResponse, SecondaryResponse,
    SecondaryStatusResponse, SecondaryTransferSummary, SecondaryTransfersResponse, TokenResponse,
    TransferResponse, TransferSummary, TsigKeyResponse, UpdateDnssecPolicyRequest,
    UpdateDnssecSettingsRequest, UpdateRecordRequest, UpdateSecondaryRequest, UpdateZoneRequest,
    VersionDetailResponse, VersionDiffResponse, VersionRecordResponse, ZonePermissionsResponse,
    ZoneResponse, ZoneStatusResponse, ZoneVersionResponse, ZoneWriteResponse,
};
use utoipa::{
    Modify, OpenApi,
    openapi::security::{Http, HttpAuthScheme, SecurityScheme},
};

/// OpenAPI document for the HTTP API, served when `api.openapi_enabled` is on.
#[derive(Debug, OpenApi)]
#[openapi(
    paths(
        super::health::handle_health,
        super::zone::list_zones,
        super::zone::get_zone,
        super::zone::create_zone,
        super::zone::update_zone,
        super::zone::delete_zone,
        super::record::list_records,
        super::record::get_record,
        super::record::create_record,
        super::record::update_record,
        super::record::delete_record,
        super::record::delete_records_matching,
        super::record::create_records_bulk,
        super::zone::import_zone,
        super::zone::export_zone,
        super::zone::list_zone_versions,
        super::zone::get_zone_version,
        super::zone::diff_zone_versions,
        super::zone::rollback_zone,
        super::zone::get_zone_status,
        super::notify::notify_all_zones,
        super::notify::notify_zone,
        super::secondary::list_secondaries,
        super::secondary::create_secondary,
        super::secondary::get_secondary,
        super::secondary::update_secondary,
        super::secondary::delete_secondary,
        super::secondary::check_secondary,
        super::secondary::list_secondary_transfers,
        super::tsig_key::list_tsig_keys,
        super::tsig_key::create_tsig_key,
        super::tsig_key::get_tsig_key,
        super::tsig_key::delete_tsig_key,
        super::token::list_tokens,
        super::token::create_token,
        super::token::get_self_token,
        super::token::list_self_token_grants,
        super::token::delete_token,
        super::role::list_roles,
        super::role::create_role,
        super::role::get_role,
        super::role::delete_role,
        super::role::list_role_grants,
        super::role::create_role_grant,
        super::role::delete_role_grant,
        super::permission::get_permissions,
        super::dnssec::get_dnssec_status,
        super::dnssec::enable_dnssec,
        super::dnssec::disable_dnssec,
        super::dnssec::sign_zone,
        super::dnssec::start_dnssec_rollover,
        super::dnssec::ds_seen_dnssec_rollover,
        super::dnssec::withdraw_dnssec,
        super::dnssec::update_dnssec_settings,
        super::dnssec::cancel_dnssec_withdrawal,
        super::dnssec::check_dnssec_ds,
        super::dnssec_policy::list_dnssec_policies,
        super::dnssec_policy::create_dnssec_policy,
        super::dnssec_policy::get_dnssec_policy,
        super::dnssec_policy::update_dnssec_policy,
        super::dnssec_policy::delete_dnssec_policy,
        super::external_dns::list_external_dns_domains,
        super::external_dns::list_external_dns_records,
        super::external_dns::apply_external_dns_changes,
        super::external_dns::adjust_external_dns_records
    ),
    components(schemas(
        BulkRecordsResponse,
        PermissionsResponse,
        PermittedActionsResponse,
        ZonePermissionsResponse,
        DeleteRecordsResponse,
        CreateBulkRecordsRequest,
        CreateDnssecPolicyRequest,
        CreateRecordRequest,
        CreateSecondaryRequest,
        CreateTsigKeyRequest,
        CreateZoneRequest,
        CreateRoleGrantRequest,
        CreateRoleRequest,
        CreateTokenRequest,
        CreatedTokenResponse,
        DnssecDelegationInfo,
        DnssecDelegationKeyInfo,
        DnssecDsInfo,
        DnssecKeyInfo,
        DnssecPolicyResponse,
        DnssecStatusResponse,
        EnableDnssecRequest,
        ErrorResponse,
        ExternalDnsAdjustRequest,
        ExternalDnsAdjustResponse,
        ExternalDnsChangesRequest,
        ExternalDnsChangesResponse,
        ExternalDnsRecord,
        ExternalDnsRecordUpdate,
        ExternalDnsRecordsResponse,
        ExternalDnsDomainsResponse,
        GetDnssecPolicyResponse,
        GetRecordResponse,
        GetSecondaryResponse,
        GetTsigKeyResponse,
        GetZoneResponse,
        GetRoleGrantResponse,
        GetRoleResponse,
        GetTokenResponse,
        HealthResponse,
        HealthStatus,
        ImportSummary,
        ImportZoneRequest,
        DeleteZoneResponse,
        ImportZoneResponse,
        MessageResponse,
        PaginatedResponse<GetRecordResponse>,
        PaginatedResponse<GetDnssecPolicyResponse>,
        PaginatedResponse<GetSecondaryResponse>,
        PaginatedResponse<GetRoleGrantResponse>,
        PaginatedResponse<GetRoleResponse>,
        PaginatedResponse<GetTokenResponse>,
        PaginatedResponse<GetTsigKeyResponse>,
        PaginatedResponse<GetZoneResponse>,
        PaginatedResponse<ZoneVersionResponse>,
        Pagination,
        RecordDiff,
        RecordDiffEntry,
        RecordDiffSummary,
        RecordDiffValue,
        RecordItem,
        RecordResponse,
        RecordWriteResponse,
        RecordValueRequest,
        RollbackSummary,
        RollbackZoneResponse,
        RolloverDnssecRequest,
        NotifyCheckResponse,
        TransferKind,
        TransferResult,
        TransferResponse,
        TransferSummary,
        SecondaryTransfersResponse,
        SecondaryTransferSummary,
        SecondaryCheckResponse,
        SecondaryResponse,
        SecondaryStatusResponse,
        UpdateDnssecPolicyRequest,
        UpdateDnssecSettingsRequest,
        UpdateRecordRequest,
        UpdateSecondaryRequest,
        UpdateZoneRequest,
        VersionDetailResponse,
        VersionDiffResponse,
        VersionRecordResponse,
        TsigKeyResponse,
        ZoneResponse,
        ZoneWriteResponse,
        ZoneVersionResponse,
        ZoneStatusResponse,
        Action,
        RoleGrantResponse,
        RoleResponse,
        TokenResponse
    )),
    // Global requirement; /health opts out with an empty per-path security.
    security(
        ("bearer_auth" = [])
    ),
    modifiers(&SecurityAddon),
    tags(
        (name = "Health", description = "Service health probe for load balancers and orchestrators."),
        (name = "Zone", description = "Manage DNS zones including creation, update, deletion, and retrieval."),
        (name = "Record", description = "Manage DNS records including creation, update, deletion, and retrieval."),
        (name = "Notify", description = "Send DNS NOTIFY messages to secondary servers."),
        (name = "Secondary", description = "The secondary servers: each receives NOTIFY, may pull zones unsigned from its address, and is probed for the serial it serves."),
        (name = "TSIG", description = "Manage TSIG keys, each authenticating nsupdate and transfers into a role."),
        (name = "Token", description = "API tokens, each authenticating into a role."),
        (name = "Role", description = "Roles and their grants: the actions API tokens and TSIG keys holding a role may perform."),
        (name = "DNSSEC", description = "DNSSEC policies (the signing-parameter bundles zones sign under) and per-zone signing: enable, disable, status, DS records for the parent zone and the parent's check of them, key rollover, and re-signing."),
        (name = "ExternalDNS", description = "Provider endpoints for the ExternalDNS webhook adapter; registered only when api.external_dns_enabled is set.")
    ),
    info(
        title = "Bindizr HTTP API",
        version = env!("CARGO_PKG_VERSION"),
        description = "This is the API documentation for Bindizr",
        contact(email = "kevin136583@gmail.com"),
        license(name = "Apache 2.0", url = "http://www.apache.org/licenses/LICENSE-2.0.html")
    )
)]
#[derive(Clone, PartialEq, Eq, Copy)]
pub(crate) struct ApiDoc;

#[derive(Debug, Clone, PartialEq, Eq, Copy)]

struct SecurityAddon;

impl Modify for SecurityAddon {
    /// Add bearer-token authentication to the OpenAPI document.
    fn modify(&self, openapi: &mut utoipa::openapi::OpenApi) {
        if let Some(components) = openapi.components.as_mut() {
            components.add_security_scheme(
                "bearer_auth",
                SecurityScheme::Http(Http::new(HttpAuthScheme::Bearer)),
            );
        }
    }
}
