use bindizr_service::types::{
    BulkRecordsResponse, CreateBulkRecordsRequest, CreateRecordRequest, CreateTsigKeyRequest,
    CreateZoneRequest, CreateZoneTokenPolicyRequest, CreateZoneTsigPolicyRequest, DnssecCheckInfo,
    DnssecDsInfo, DnssecDsListResponse, DnssecKeyInfo, DnssecStatusResponse, DnssecTimingInfo,
    EnableDnssecRequest, ErrorResponse, ExternalDnsAdjustRequest, ExternalDnsAdjustResponse,
    ExternalDnsChangesRequest, ExternalDnsChangesResponse, ExternalDnsRecordItem,
    ExternalDnsRecordsResponse, ExternalDnsRrset, ExternalDnsRrsetUpdate, ExternalDnsZonesResponse,
    GetDnssecStatusResponse, GetRecordResponse, GetTsigKeyResponse, GetZoneResponse,
    GetZoneTokenPolicyResponse, GetZoneTsigPolicyResponse, HealthResponse, ImportMode,
    ImportSummary, ImportZoneFileRequest, ImportZoneFileResponse, MessageResponse,
    NotifyZoneRequest, PaginatedResponse, Pagination, RecordDiff, RecordDiffEntry,
    RecordDiffSummary, RecordDiffValue, RecordItem, RecordResponse, RecordValueRequest,
    RollbackSummary, RollbackZoneRequest, RollbackZoneResponse, RolloverDnssecRequest,
    SecondaryStatusResponse, SetDnssecTimingRequest, TsigKeyListResponse, TsigKeyResponse,
    VerifyDnssecResponse, VersionDetailResponse, VersionDiffResponse, VersionRecordResponse,
    ZoneDetailResponse, ZoneResponse, ZoneStatusResponse, ZoneTokenPolicyListResponse,
    ZoneTokenPolicyResponse, ZoneTsigPolicyListResponse, ZoneTsigPolicyResponse,
    ZoneVersionResponse,
};
use utoipa::{
    Modify, OpenApi,
    openapi::security::{Http, HttpAuthScheme, SecurityScheme},
};

/// OpenAPI document for the HTTP API, served when `api.openapi_enabled` is on.
#[derive(OpenApi)]
#[openapi(
    paths(
        super::health::get_health,
        super::zone::get_zones,
        super::zone::get_zone,
        super::zone::create_zone,
        super::zone::update_zone,
        super::zone::delete_zone,
        super::record::get_records,
        super::record::get_record,
        super::record::create_record,
        super::record::update_record,
        super::record::delete_record,
        super::record::create_records_bulk,
        super::zone::import_zone,
        super::zone::export_zone,
        super::zone::list_zone_versions,
        super::zone::get_zone_version,
        super::zone::diff_zone_versions,
        super::zone::rollback_zone,
        super::zone::get_zone_status,
        super::notify::notify_zones,
        super::tsig_key::get_tsig_keys,
        super::tsig_key::create_tsig_key,
        super::tsig_key::get_tsig_key,
        super::tsig_key::delete_tsig_key,
        super::tsig_key::get_zone_tsig_policies,
        super::tsig_key::create_zone_tsig_policy,
        super::tsig_key::delete_zone_tsig_policy,
        super::token_policy::get_zone_token_policies,
        super::token_policy::create_zone_token_policy,
        super::token_policy::delete_zone_token_policy,
        super::dnssec::get_dnssec_status,
        super::dnssec::enable_dnssec,
        super::dnssec::disable_dnssec,
        super::dnssec::get_dnssec_ds_records,
        super::dnssec::sign_zone,
        super::dnssec::start_dnssec_rollover,
        super::dnssec::ds_seen_dnssec_rollover,
        super::dnssec::withdraw_dnssec,
        super::dnssec::set_dnssec_timing,
        super::dnssec::cancel_dnssec_withdrawal,
        super::dnssec::verify_dnssec,
        super::external_dns::get_external_dns_zones,
        super::external_dns::get_external_dns_records,
        super::external_dns::apply_external_dns_changes,
        super::external_dns::adjust_external_dns_rrsets
    ),
    components(schemas(
        BulkRecordsResponse,
        CreateBulkRecordsRequest,
        CreateRecordRequest,
        CreateTsigKeyRequest,
        CreateZoneRequest,
        CreateZoneTokenPolicyRequest,
        CreateZoneTsigPolicyRequest,
        DnssecDsInfo,
        DnssecDsListResponse,
        DnssecKeyInfo,
        DnssecCheckInfo,
        DnssecStatusResponse,
        DnssecTimingInfo,
        EnableDnssecRequest,
        ErrorResponse,
        ExternalDnsAdjustRequest,
        ExternalDnsAdjustResponse,
        ExternalDnsChangesRequest,
        ExternalDnsChangesResponse,
        ExternalDnsRecordItem,
        ExternalDnsRecordsResponse,
        ExternalDnsRrset,
        ExternalDnsRrsetUpdate,
        ExternalDnsZonesResponse,
        GetDnssecStatusResponse,
        VerifyDnssecResponse,
        GetRecordResponse,
        GetTsigKeyResponse,
        GetZoneResponse,
        GetZoneTokenPolicyResponse,
        GetZoneTsigPolicyResponse,
        HealthResponse,
        ImportMode,
        ImportSummary,
        ImportZoneFileRequest,
        ImportZoneFileResponse,
        MessageResponse,
        NotifyZoneRequest,
        PaginatedResponse<GetRecordResponse>,
        PaginatedResponse<GetZoneResponse>,
        PaginatedResponse<ZoneVersionResponse>,
        Pagination,
        RecordDiff,
        RecordDiffEntry,
        RecordDiffSummary,
        RecordDiffValue,
        RecordItem,
        RecordResponse,
        RecordValueRequest,
        RollbackSummary,
        RollbackZoneRequest,
        RollbackZoneResponse,
        RolloverDnssecRequest,
        SecondaryStatusResponse,
        SetDnssecTimingRequest,
        VersionDetailResponse,
        VersionDiffResponse,
        VersionRecordResponse,
        TsigKeyListResponse,
        TsigKeyResponse,
        ZoneDetailResponse,
        ZoneResponse,
        ZoneVersionResponse,
        ZoneStatusResponse,
        ZoneTokenPolicyListResponse,
        ZoneTokenPolicyResponse,
        ZoneTsigPolicyListResponse,
        ZoneTsigPolicyResponse
    )),
    // Global requirement; /health opts out with an empty per-path security.
    security(
        ("bearer_auth" = [])
    ),
    modifiers(&SecurityAddon),
    tags(
        (name = "Health", description = "Service health probe for load balancers and orchestrators."),
        (name = "Zone", description = "Manage DNS zones including creation, update, deletion, and retrieval."),
        (name = "Record", description = "Manage DNS records including creation, update, deletion, and retrieval."),
        (name = "Notify", description = "Send DNS NOTIFY messages to secondary servers."),
        (name = "TSIG", description = "Manage TSIG keys and per-zone TSIG policies for nsupdate authentication."),
        (name = "Token", description = "Per-zone API token policies: record-plane grants for scoped tokens."),
        (name = "DNSSEC", description = "Per-zone DNSSEC signing: enable, disable, status, DS records for the parent zone, key rollover, and re-signing."),
        (name = "ExternalDNS", description = "Provider endpoints for the ExternalDNS webhook adapter; registered only when api.external_dns_enabled is set.")
    ),
    info(
        title = "Bindizr HTTP API",
        version = env!("CARGO_PKG_VERSION"),
        description = "This is the API documentation for Bindizr",
        contact(email = "kevin136583@gmail.com"),
        license(name = "Apache 2.0", url = "http://www.apache.org/licenses/LICENSE-2.0.html")
    )
)]
pub(crate) struct ApiDoc;

struct SecurityAddon;

impl Modify for SecurityAddon {
    fn modify(&self, openapi: &mut utoipa::openapi::OpenApi) {
        if let Some(components) = openapi.components.as_mut() {
            components.add_security_scheme(
                "bearer_auth",
                SecurityScheme::Http(Http::new(HttpAuthScheme::Bearer)),
            );
        }
    }
}
