//! Completion scripts and the man page, generated from the clap command the
//! binary parses with, so they cannot drift from `--help`.

use bindizr_core::stream::write_stdout;
use clap::CommandFactory;
use clap_complete::Shell;

use crate::cli::{Args, error::CliError};

/// Print the completion script for `shell` on stdout.
pub(crate) fn handle_command(shell: Shell) -> Result<(), CliError> {
    let mut command = Args::command();
    let name = command.get_name().to_string();
    let mut script = Vec::new();
    clap_complete::generate(shell, &mut command, name, &mut script);
    write_generated(&script)
}

/// Print the roff man page for `bindizr` on stdout.
pub(crate) fn handle_man_command() -> Result<(), CliError> {
    let mut page = Vec::new();
    clap_mangen::Man::new(Args::command())
        .render(&mut page)
        .map_err(|e| CliError::from(format!("Failed to render the man page: {}", e)))?;
    write_generated(&page)
}

/// Write generated bytes to stdout as text; both outputs are ASCII roff or
/// shell script.
fn write_generated(bytes: &[u8]) -> Result<(), CliError> {
    let text = std::str::from_utf8(bytes)
        .map_err(|e| CliError::from(format!("Generated output was not UTF-8: {}", e)))?;
    write_stdout(text);
    Ok(())
}
