{{- if not .Values.tsig.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bindizr-stack.tsigSecretName" . }}
  labels:
    {{- include "bindizr-stack.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.tsig.keyName }}: {{ required "Set tsig.secret or tsig.existingSecret" .Values.tsig.secret | quote }}
{{- end }}
---
{{- if and (not .Values.bindizr.database.existingSecret) (ne .Values.bindizr.database.type "sqlite") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bindizr-stack.databaseSecretName" . }}
  labels:
    {{- include "bindizr-stack.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.bindizr.database.secretKey }}: {{ required "Set bindizr.database.serverUrl or bindizr.database.existingSecret" .Values.bindizr.database.serverUrl | quote }}
{{- end }}
