{{- if and (not .Values.tsig.existingSecret) .Values.tsig.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bindizr-stack.tsigSecretName" . }}
  labels:
    {{- include "bindizr-stack.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.tsig.keyName }}: {{ .Values.tsig.secret | quote }}
{{- end }}
---
{{- if and (not .Values.bindizr.database.existingSecret) (ne .Values.bindizr.database.type "sqlite") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bindizr-stack.databaseSecretName" . }}
  labels:
    {{- include "bindizr-stack.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.bindizr.database.secretKey }}: {{ include "bindizr-stack.databaseUrl" . | quote }}
{{- end }}
