{{- if and (not .Values.tsig.existingSecret) .Values.tsig.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bindizr-stack.tsigSecretName" . }}
  labels:
    {{- include "bindizr-stack.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.tsig.keyName }}: {{ .Values.tsig.secret | quote }}
{{- end }}
---
{{- if not .Values.bindizr.database.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bindizr-stack.databaseSecretName" . }}
  labels:
    {{- include "bindizr-stack.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.bindizr.database.secretKey }}: {{ include "bindizr-stack.databaseUrl" . | quote }}
{{- end }}
{{- if .Values.mysql.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bindizr-stack.mysql.fullname" . }}
  labels:
    {{- include "bindizr-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: mysql
type: Opaque
stringData:
  mysql-password: {{ .Values.mysql.auth.password | quote }}
  mysql-root-password: {{ .Values.mysql.auth.rootPassword | quote }}
{{- end }}
{{- if .Values.postgresql.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bindizr-stack.postgresql.fullname" . }}
  labels:
    {{- include "bindizr-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
type: Opaque
stringData:
  postgres-password: {{ .Values.postgresql.auth.password | quote }}
{{- end }}
