apiVersion: v2
name: bindizr-stack
description: Bindizr DNS control plane with BIND9 authoritative DNS pods.
type: application
version: 0.1.0
appVersion: "0.1.0-beta.4"
keywords:
  - dns
  - bindizr
  - bind9
dependencies:
  - name: mysql
    version: ">=12.0.0"
    repository: "https://charts.bitnami.com/bitnami"
    condition: mysql.enabled
  - name: postgresql
    version: ">=15.0.0"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
