apiVersion: v2
name: bindizr-stack
description: Bindizr DNS control plane with BIND9 authoritative DNS pods.
type: application
version: 0.1.0-beta.5
appVersion: "0.1.0-beta.5"
home: https://github.com/kweonminsung/bindizr
sources:
  - https://github.com/kweonminsung/bindizr
maintainers:
  - name: kweonminsung
    email: kevin136583@gmail.com
keywords:
  - dns
  - bindizr
  - bind9
  - kubernetes
  - helm
