[package]
name = "bindizr-e2e"
version.workspace = true
edition.workspace = true
publish = false
autotests = false

[[bin]]
name = "bindizr-e2e-server"
path = "src/bin/bindizr.rs"

[[bin]]
name = "bindizr-e2e-external-dns"
path = "src/bin/external_dns.rs"

[[test]]
name = "e2e"
path = "tests/e2e.rs"

[dependencies]
bindizr = { path = "../bindizr" }
bindizr-external-dns = { path = "../bindizr-external-dns" }
tokio.workspace = true

[dev-dependencies]
domain.workspace = true
reqwest.workspace = true
serde_json.workspace = true
serial_test.workspace = true
tempfile.workspace = true
