name: CI

on:
  # push:
  #   branches: [ "main" ]
  pull_request:
    branches: [ "main", "develop" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v7

    - name: Build
      run: cargo build --verbose -p bindizr
      
    - name: Run tests
      run: cargo test --workspace --all-features --verbose -- --test-threads=1
